---
title: "Using optimall"
author: "Jasper Yang"
date: "Last updated: `r format(Sys.Date(), '%B %d, %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{optimall-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(optimall)
```


## Introduction

When a study population is composed of heterogeneous subpopulations, stratified random sampling techniques are often employed to obtain more precise estimates of population characteristics. Efficiently allocating samples to strata under this method is a crucial step in the study design, especially when sampling is expensive. 

`optimall` offers a collection of functions that are designed to streamline the process of optimum sample allocation, specifically under an adaptive, multi-phase approach. Its main functions allow users to:

* Split existing strata into smaller strata based on values or percentiles of other variables.

* Calculate the optimum number of samples to allocate to each stratum in a given study in order to minimize the variance of an estimate of interest. 

* Optimally allocate a fixed number of samples to an ancillary sampling wave based on results from a prior wave. 

When used together, these functions can automate most of the sampling workflow. This vignette will introduce the theoretical framework behind the functions before demonstrating how they can be used to work with sampling data in R.

## Optimal Allocation
Assuming that the per-unit sampling cost is the same in each stratum and that $S_h$, the standard deviation within each stratum, can be estimated, Neyman (1934) presented the following solution to optimally allocate $n$ samples among $H$ strata:  

$$n_h = n \frac{N_hS_h}{\sum_{i=1}^H N_iS_i}$$
This formula, known as Neyman allocation, is widely used as a robust method for minimizing the variance of an estimate. It can be called 

Wright (2014) presents a

`optimall` allows users to select between Neyman allocation, Wright Algorithm I, and Wright Algorithm II in the `method` argument of the `optim

## Adaptive, Multi-Wave Sampling


## Example workflow: using `optimall` to work with Healthy Weight Data
* Introduce the given, error prone, data. We call this the "phase I" data according to the the notation from McIsaac

* Show how the strata are created and, briefly, why

* We have 250 samples for wave 1, let's optimally allocate them in order to minimize y.

* Gather samples, allocate_wave for next 250.

* Look at results, decide to one split strata further, then re-allocate wave. 


## References
